# Generated by Django 4.2 on 2023-04-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='artist',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='img',
            field=models.URLField(blank=True),
        ),
    ]
