# Generated by Django 4.2 on 2023-04-04 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0005_remove_song_artists_artist_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='jams.song'),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_art',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='publish_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jams.album'),
        ),
    ]
