# Generated by Django 4.2 on 2023-04-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0009_alter_artist_name_alter_song_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='songs',
        ),
    ]
