# Generated by Django 4.2 on 2023-04-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0010_remove_artist_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='artist',
            field=models.ManyToManyField(to='jams.artist'),
        ),
    ]
